const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/auth");
const adminController = require("../controllers/adminController");
const adminSubjectController = require("../controllers/adminSubjectController");
router.get(
  "/admin-student",
  authMiddleware,
  adminController.adminStudentPage
);
router.get(
  "/admin-class",
  authMiddleware,
  adminController.adminClassPage
);
router.get(
  "/admin-dashboard",
  authMiddleware,
  adminController.schoolDashboardPage
);
router.get(
  "/school-dashboard",
  authMiddleware,
  adminController.schoolDashboardPage
);
router.post(
  "/admin/map-class-subject",
  authMiddleware,
  adminController.mapClassSubject
);
router.get(
  "/admin-settings",
  authMiddleware,
  adminController.adminSettingsPage
);
router.post(
  "/admin/add-user",
  authMiddleware,
  adminController.addUserFromAdmin
);
router.post(
  "/admin/create-class",
  authMiddleware,
  adminController.createClassFromAdmin
);
router.post(
  "/admin/delete-class",
  authMiddleware,
  adminController.deleteClassFromAdmin
);
router.post(
  "/admin/create-subject",
  authMiddleware,
  adminSubjectController.createSubjectFromAdmin
);
router.post(
  "/admin/delete-subject",
  authMiddleware,
  adminSubjectController.deleteSubjectFromAdmin
);
router.post(
  "/admin/create-student",
  authMiddleware,
  adminController.createStudentFromAdmin
);
router.post(
  "/admin/bulk-create-students",
  authMiddleware,
  adminController.bulkCreateStudentsFromAdmin
);
router.post(
  "/admin/update-student-class",
  authMiddleware,
  adminController.updateStudentClassFromAdmin
);
router.post(
  "/admin/delete-student",
  authMiddleware,
  adminController.deleteStudentFromAdmin
);
router.post(
  "/admin/delete-class-subject-mapping",
  authMiddleware,
  adminController.deleteClassSubjectMapping
);
router.post(
  "/admin/delete-user",
  authMiddleware,
  adminController.deleteUserFromAdmin
);
module.exports = router;