const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/auth");
const adminController = require("../controllers/adminController");
const adminSubjectController = require("../controllers/adminSubjectController");
router.get(
  "/admin-student",
  authMiddleware,
  adminController.adminStudentPage
);
router.get(
  "/admin-class",
  authMiddleware,
  adminController.adminClassPage
);
router.get(
  "/admin-dashboard",
  authMiddleware,
  adminController.schoolDashboardPage
);
router.get(
  "/school-dashboard",
  authMiddleware,
  adminController.schoolDashboardPage
);
router.post(
  "/api/admin/mappings/create",
  authMiddleware,
  adminController.mapClassSubject
);
router.get(
  "/admin-settings",
  authMiddleware,
  adminController.adminSettingsPage
);
router.get(
  "/api/admin-settings-data",
  authMiddleware,
  adminController.adminSettingsData
);
router.post(
  "/api/admin/users/create",
  authMiddleware,
  adminController.addUserFromAdmin
);
router.post(
  "/api/admin/classes/create",
  authMiddleware,
  adminController.createClassFromAdmin
);
router.post(
  "/api/admin/classes/delete",
  authMiddleware,
  adminController.deleteClassFromAdmin
);
router.post(
  "/api/admin/subjects/create",
  authMiddleware,
  adminSubjectController.createSubjectFromAdmin
);
router.post(
  "/api/admin/subjects/delete",
  authMiddleware,
  adminSubjectController.deleteSubjectFromAdmin
);
router.post(
  "/admin/create-student",
  authMiddleware,
  adminController.createStudentFromAdmin
);
router.post(
  "/api/admin/students/create",
  authMiddleware,
  adminController.createStudentFromAdmin
);
router.post(
  "/api/admin/students/bulk-create",
  authMiddleware,
  adminController.bulkCreateStudentsFromAdmin
);
router.post(
  "/api/admin/students/update-class",
  authMiddleware,
  adminController.updateStudentClassFromAdmin
);
router.post(
  "/api/admin/students/delete",
  authMiddleware,
  adminController.deleteStudentFromAdmin
);
router.post(
  "/api/admin/mappings/delete",
  authMiddleware,
  adminController.deleteClassSubjectMapping
);
router.post(
  "/api/admin/users/delete",
  authMiddleware,
  adminController.deleteUserFromAdmin
);
module.exports = router;